addSbtPlugin("com.github.sbt"      % "sbt-jacoco"               % "3.4.0")
addSbtPlugin("pl.project13.scala"  % "sbt-jmh"                  % "0.4.4")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"             % "1.1.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.13.2")
