name: test

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "checkout reference (sha/branch)"
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-15, ubuntu-22.04, windows-2025, ubuntu-24.04-arm]
        java-version: [17]

    env:
      JAVA_OPTS: -Xmx4g

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version}}
          distribution: "zulu"

      - uses: sbt/setup-sbt@v1

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install jsdom
        run: npm install jsdom

      - name: start sbt
        run: sbt --client update

      - name: compile
        run: sbt --client compile

      - name: documentation
        run: sbt --client doc
        continue-on-error: true

      - name: compile tests
        run: sbt --client Test/compile

      - name: compile tests js
        run: sbt --client Test/fastLinkJS

      - name: compile tests native
        run: sbt --client Test/nativeLink

      - name: test
        run: sbt --client test
